version: '3.1'
services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password